/**
 * Transaction type: `adjustment`, `advance`, `advance_funding`, `anticipation_repayment`, `application_fee`, `application_fee_refund`, `charge`, `climate_order_purchase`, `climate_order_refund`, `connect_collection_transfer`, `contribution`, `issuing_authorization_hold`, `issuing_authorization_release`, `issuing_dispute`, `issuing_transaction`, `obligation_outbound`, `obligation_reversal_inbound`, `payment`, `payment_failure_refund`, `payment_network_reserve_hold`, `payment_network_reserve_release`, `payment_refund`, `payment_reversal`, `payment_unreconciled`, `payout`, `payout_cancel`, `payout_failure`, `payout_minimum_balance_hold`, `payout_minimum_balance_release`, `refund`, `refund_failure`, `reserve_transaction`, `reserved_funds`, `stripe_fee`, `stripe_fx_fee`, `stripe_balance_payment_debit`, `stripe_balance_payment_debit_reversal`, `tax_fee`, `topup`, `topup_reversal`, `transfer`, `transfer_cancel`, `transfer_failure`, or `transfer_refund`. Learn more about [balance transaction types and what they represent](https://stripe.com/docs/reports/balance-transaction-types). To classify transactions for accounting purposes, consider `reporting_category` instead.
 */
export type BalanceTransactionTypeEnum =
  | "adjustment"
  | "advance"
  | "advance_funding"
  | "anticipation_repayment"
  | "application_fee"
  | "application_fee_refund"
  | "charge"
  | "climate_order_purchase"
  | "climate_order_refund"
  | "connect_collection_transfer"
  | "contribution"
  | "issuing_authorization_hold"
  | "issuing_authorization_release"
  | "issuing_dispute"
  | "issuing_transaction"
  | "obligation_outbound"
  | "obligation_reversal_inbound"
  | "payment"
  | "payment_failure_refund"
  | "payment_network_reserve_hold"
  | "payment_network_reserve_release"
  | "payment_refund"
  | "payment_reversal"
  | "payment_unreconciled"
  | "payout"
  | "payout_cancel"
  | "payout_failure"
  | "payout_minimum_balance_hold"
  | "payout_minimum_balance_release"
  | "refund"
  | "refund_failure"
  | "reserve_transaction"
  | "reserved_funds"
  | "stripe_balance_payment_debit"
  | "stripe_balance_payment_debit_reversal"
  | "stripe_fee"
  | "stripe_fx_fee"
  | "tax_fee"
  | "topup"
  | "topup_reversal"
  | "transfer"
  | "transfer_cancel"
  | "transfer_failure"
  | "transfer_refund";
