/**
 * CustomerSubscriptionCreateBodyPaymentSettingsPaymentMethodOptionsUsBankAccountObj0FinancialConnectionsFiltersAccountSubcategoriesItemEnum
 */
export type CustomerSubscriptionCreateBodyPaymentSettingsPaymentMethodOptionsUsBankAccountObj0FinancialConnectionsFiltersAccountSubcategoriesItemEnum =
  | "checking"
  | "savings";
