/**
 * CustomerSubscriptionModifyBodyPaymentSettingsPaymentMethodOptionsUsBankAccountObj0FinancialConnectionsFiltersAccountSubcategoriesItemEnum
 */
export type CustomerSubscriptionModifyBodyPaymentSettingsPaymentMethodOptionsUsBankAccountObj0FinancialConnectionsFiltersAccountSubcategoriesItemEnum =
  | "checking"
  | "savings";
