import { External$Mandate, Mandate, Schemas$Mandate } from "./mandate";
import {
  External$PaymentMethod,
  PaymentMethod,
  Schemas$PaymentMethod,
} from "./payment-method";
import { zodTransform } from "@sideko-inc/stripe/core";
import * as z from "zod";

export type PaymentMethodDetailsIdeal = {
  /**
   * The customer's bank. Can be one of `abn_amro`, `asn_bank`, `bunq`, `handelsbanken`, `ing`, `knab`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
   */
  bank?:
    | (
        | "abn_amro"
        | "asn_bank"
        | "bunq"
        | "handelsbanken"
        | "ing"
        | "knab"
        | "moneyou"
        | "n26"
        | "nn"
        | "rabobank"
        | "regiobank"
        | "revolut"
        | "sns_bank"
        | "triodos_bank"
        | "van_lanschot"
        | "yoursafe"
      )
    | null
    | undefined;
  /**
   * The Bank Identifier Code of the customer's bank.
   */
  bic?:
    | (
        | "ABNANL2A"
        | "ASNBNL21"
        | "BITSNL2A"
        | "BUNQNL2A"
        | "FVLBNL22"
        | "HANDNL2A"
        | "INGBNL2A"
        | "KNABNL2H"
        | "MOYONL21"
        | "NNBANL2G"
        | "NTSBDEB1"
        | "RABONL2U"
        | "RBRBNL21"
        | "REVOIE23"
        | "REVOLT21"
        | "SNSBNL2A"
        | "TRIONL2U"
      )
    | null
    | undefined;
  /**
   * The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
   */
  generatedSepaDebit?: (string | PaymentMethod) | undefined;
  /**
   * The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
   */
  generatedSepaDebitMandate?: (string | Mandate) | undefined;
  /**
   * Last four characters of the IBAN.
   */
  ibanLast4?: string | null | undefined;
  /**
   * Owner's verified full name. Values are verified or provided by iDEAL directly
   * (if supported) at the time of authorization or settlement. They cannot be set or mutated.
   */
  verifiedName?: string | null | undefined;
};

/**
 * @internal
 * PaymentMethodDetailsIdeal without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$PaymentMethodDetailsIdeal = {
  bank?:
    | (
        | "abn_amro"
        | "asn_bank"
        | "bunq"
        | "handelsbanken"
        | "ing"
        | "knab"
        | "moneyou"
        | "n26"
        | "nn"
        | "rabobank"
        | "regiobank"
        | "revolut"
        | "sns_bank"
        | "triodos_bank"
        | "van_lanschot"
        | "yoursafe"
      )
    | null
    | undefined;
  bic?:
    | (
        | "ABNANL2A"
        | "ASNBNL21"
        | "BITSNL2A"
        | "BUNQNL2A"
        | "FVLBNL22"
        | "HANDNL2A"
        | "INGBNL2A"
        | "KNABNL2H"
        | "MOYONL21"
        | "NNBANL2G"
        | "NTSBDEB1"
        | "RABONL2U"
        | "RBRBNL21"
        | "REVOIE23"
        | "REVOLT21"
        | "SNSBNL2A"
        | "TRIONL2U"
      )
    | null
    | undefined;
  generated_sepa_debit?: (string | External$PaymentMethod) | undefined;
  generated_sepa_debit_mandate?: (string | External$Mandate) | undefined;
  iban_last4?: string | null | undefined;
  verified_name?: string | null | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object PaymentMethodDetailsIdeal
 */
const SchemaIn$PaymentMethodDetailsIdeal: z.ZodType<
  PaymentMethodDetailsIdeal, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    bank: z
      .enum([
        "abn_amro",
        "asn_bank",
        "bunq",
        "handelsbanken",
        "ing",
        "knab",
        "moneyou",
        "n26",
        "nn",
        "rabobank",
        "regiobank",
        "revolut",
        "sns_bank",
        "triodos_bank",
        "van_lanschot",
        "yoursafe",
      ])
      .nullable()
      .optional(),
    bic: z
      .enum([
        "ABNANL2A",
        "ASNBNL21",
        "BITSNL2A",
        "BUNQNL2A",
        "FVLBNL22",
        "HANDNL2A",
        "INGBNL2A",
        "KNABNL2H",
        "MOYONL21",
        "NNBANL2G",
        "NTSBDEB1",
        "RABONL2U",
        "RBRBNL21",
        "REVOIE23",
        "REVOLT21",
        "SNSBNL2A",
        "TRIONL2U",
      ])
      .nullable()
      .optional(),
    generated_sepa_debit: z
      .union([z.string(), z.lazy(() => Schemas$PaymentMethod.in)])
      .optional(),
    generated_sepa_debit_mandate: z
      .union([z.string(), z.lazy(() => Schemas$Mandate.in)])
      .optional(),
    iban_last4: z.string().nullable().optional(),
    verified_name: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      bank: "bank",
      bic: "bic",
      generated_sepa_debit: "generatedSepaDebit",
      generated_sepa_debit_mandate: "generatedSepaDebitMandate",
      iban_last4: "ibanLast4",
      verified_name: "verifiedName",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$PaymentMethodDetailsIdeal
 */
const SchemaOut$PaymentMethodDetailsIdeal: z.ZodType<
  External$PaymentMethodDetailsIdeal, // output type of this zod object
  z.ZodTypeDef,
  PaymentMethodDetailsIdeal // the object to be transformed
> = z
  .object({
    bank: z
      .enum([
        "abn_amro",
        "asn_bank",
        "bunq",
        "handelsbanken",
        "ing",
        "knab",
        "moneyou",
        "n26",
        "nn",
        "rabobank",
        "regiobank",
        "revolut",
        "sns_bank",
        "triodos_bank",
        "van_lanschot",
        "yoursafe",
      ])
      .nullable()
      .optional(),
    bic: z
      .enum([
        "ABNANL2A",
        "ASNBNL21",
        "BITSNL2A",
        "BUNQNL2A",
        "FVLBNL22",
        "HANDNL2A",
        "INGBNL2A",
        "KNABNL2H",
        "MOYONL21",
        "NNBANL2G",
        "NTSBDEB1",
        "RABONL2U",
        "RBRBNL21",
        "REVOIE23",
        "REVOLT21",
        "SNSBNL2A",
        "TRIONL2U",
      ])
      .nullable()
      .optional(),
    generatedSepaDebit: z
      .union([z.string(), z.lazy(() => Schemas$PaymentMethod.out)])
      .optional(),
    generatedSepaDebitMandate: z
      .union([z.string(), z.lazy(() => Schemas$Mandate.out)])
      .optional(),
    ibanLast4: z.string().nullable().optional(),
    verifiedName: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      bank: "bank",
      bic: "bic",
      generatedSepaDebit: "generated_sepa_debit",
      generatedSepaDebitMandate: "generated_sepa_debit_mandate",
      ibanLast4: "iban_last4",
      verifiedName: "verified_name",
    });
  });

export const Schemas$PaymentMethodDetailsIdeal = {
  in: SchemaIn$PaymentMethodDetailsIdeal,
  out: SchemaOut$PaymentMethodDetailsIdeal,
};
