/**
 * Reason for cancellation of this PaymentIntent, either user-provided (`duplicate`, `fraudulent`, `requested_by_customer`, or `abandoned`) or generated by Stripe internally (`failed_invoice`, `void_invoice`, `automatic`, or `expired`).
 */
export type PaymentIntentCancellationReasonEnum =
  | "abandoned"
  | "automatic"
  | "duplicate"
  | "expired"
  | "failed_invoice"
  | "fraudulent"
  | "requested_by_customer"
  | "void_invoice";
