import { types } from "@sideko-inc/stripe";

/**
 * An optional filter on the list, based on the object `type` field. Without the filter, the list includes all current and future payment method types. If your integration expects only one type of payment method in the response, make sure to provide a type value in the request.
 */
export type PaymentMethodListTypeEnum =
  | "acss_debit"
  | "affirm"
  | "afterpay_clearpay"
  | "alipay"
  | "alma"
  | "amazon_pay"
  | "au_becs_debit"
  | "bacs_debit"
  | "bancontact"
  | "billie"
  | "blik"
  | "boleto"
  | "card"
  | "cashapp"
  | "customer_balance"
  | "eps"
  | "fpx"
  | "giropay"
  | "grabpay"
  | "ideal"
  | "kakao_pay"
  | "klarna"
  | "konbini"
  | "kr_card"
  | "link"
  | "mobilepay"
  | "multibanco"
  | "naver_pay"
  | "nz_bank_account"
  | "oxxo"
  | "p24"
  | "pay_by_bank"
  | "payco"
  | "paynow"
  | "paypal"
  | "pix"
  | "promptpay"
  | "revolut_pay"
  | "samsung_pay"
  | "satispay"
  | "sepa_debit"
  | "sofort"
  | "swish"
  | "twint"
  | "us_bank_account"
  | "wechat_pay"
  | "zip";
