import { zodTransform } from "@sideko-inc/stripe/core";
import * as z from "zod";

export type PaymentMethodDetailsPromptpay = {
  /**
   * Bill reference generated by PromptPay
   */
  reference?: string | null | undefined;
};

/**
 * @internal
 * PaymentMethodDetailsPromptpay without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$PaymentMethodDetailsPromptpay = {
  reference?: string | null | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object PaymentMethodDetailsPromptpay
 */
const SchemaIn$PaymentMethodDetailsPromptpay: z.ZodType<
  PaymentMethodDetailsPromptpay, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    reference: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      reference: "reference",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$PaymentMethodDetailsPromptpay
 */
const SchemaOut$PaymentMethodDetailsPromptpay: z.ZodType<
  External$PaymentMethodDetailsPromptpay, // output type of this zod object
  z.ZodTypeDef,
  PaymentMethodDetailsPromptpay // the object to be transformed
> = z
  .object({
    reference: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      reference: "reference",
    });
  });

export const Schemas$PaymentMethodDetailsPromptpay = {
  in: SchemaIn$PaymentMethodDetailsPromptpay,
  out: SchemaOut$PaymentMethodDetailsPromptpay,
};
