import { zodTransform } from "@sideko-inc/stripe/core";
import * as z from "zod";

export type PaymentMethodDetailsGrabpay = {
  /**
   * Unique transaction id generated by GrabPay
   */
  transactionId?: string | null | undefined;
};

/**
 * @internal
 * PaymentMethodDetailsGrabpay without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$PaymentMethodDetailsGrabpay = {
  transaction_id?: string | null | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object PaymentMethodDetailsGrabpay
 */
const SchemaIn$PaymentMethodDetailsGrabpay: z.ZodType<
  PaymentMethodDetailsGrabpay, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    transaction_id: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      transaction_id: "transactionId",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$PaymentMethodDetailsGrabpay
 */
const SchemaOut$PaymentMethodDetailsGrabpay: z.ZodType<
  External$PaymentMethodDetailsGrabpay, // output type of this zod object
  z.ZodTypeDef,
  PaymentMethodDetailsGrabpay // the object to be transformed
> = z
  .object({
    transactionId: z.string().nullable().optional(),
  })
  .transform((obj) => {
    return zodTransform(obj, {
      transactionId: "transaction_id",
    });
  });

export const Schemas$PaymentMethodDetailsGrabpay = {
  in: SchemaIn$PaymentMethodDetailsGrabpay,
  out: SchemaOut$PaymentMethodDetailsGrabpay,
};
