import {
  External$PlanCreateBodyMetadataObj0,
  PlanCreateBodyMetadataObj0,
  Schemas$PlanCreateBodyMetadataObj0,
} from "./plan-create-body-metadata-obj0";
import {
  External$PlanCreateBodyProductObj0,
  PlanCreateBodyProductObj0,
  Schemas$PlanCreateBodyProductObj0,
} from "./plan-create-body-product-obj0";
import {
  External$PlanCreateBodyTiersItem,
  PlanCreateBodyTiersItem,
  Schemas$PlanCreateBodyTiersItem,
} from "./plan-create-body-tiers-item";
import {
  External$PlanCreateBodyTransformUsage,
  PlanCreateBodyTransformUsage,
  Schemas$PlanCreateBodyTransformUsage,
} from "./plan-create-body-transform-usage";
import { zodRequiredAny, zodTransform } from "@sideko-inc/stripe/core";
import * as z from "zod";

/**
 * PlanCreateBody
 */
export type PlanCreateBody = {
  /**
   * Whether the plan is currently available for new subscriptions. Defaults to `true`.
   */
  active?: boolean | undefined;
  /**
   * A positive integer in cents (or local equivalent) (or 0 for a free plan) representing how much to charge on a recurring basis.
   */
  amount?: number | undefined;
  /**
   * Same as `amount`, but accepts a decimal value with at most 12 decimal places. Only one of `amount` and `amount_decimal` can be set.
   */
  amountDecimal?: string | undefined;
  /**
   * Describes how to compute the price per period. Either `per_unit` or `tiered`. `per_unit` indicates that the fixed amount (specified in `amount`) will be charged per unit in `quantity` (for plans with `usage_type=licensed`), or per unit of total usage (for plans with `usage_type=metered`). `tiered` indicates that the unit pricing will be computed using a tiering strategy as defined using the `tiers` and `tiers_mode` attributes.
   */
  billingScheme?: ("per_unit" | "tiered") | undefined;
  /**
   * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
   */
  currency: string;
  /**
   * Specifies which fields in the response should be expanded.
   */
  expand?: string[] | undefined;
  /**
   * An identifier randomly generated by Stripe. Used to identify this plan when subscribing a customer. You can optionally override this ID, but the ID must be unique across all plans in your Stripe account. You can, however, use the same plan ID in both live and test modes.
   */
  id?: string | undefined;
  /**
   * Specifies billing frequency. Either `day`, `week`, `month` or `year`.
   */
  interval: "day" | "month" | "week" | "year";
  /**
   * The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).
   */
  intervalCount?: number | undefined;
  /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
   */
  metadata?: (PlanCreateBodyMetadataObj0 | string) | undefined;
  /**
   * The meter tracking the usage of a metered price
   */
  meter?: string | undefined;
  /**
   * A brief description of the plan, hidden from customers.
   */
  nickname?: string | undefined;
  product?: (PlanCreateBodyProductObj0 | string) | undefined;
  /**
   * Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.
   */
  tiers?: PlanCreateBodyTiersItem[] | undefined;
  /**
   * Defines if the tiering price should be `graduated` or `volume` based. In `volume`-based tiering, the maximum quantity within a period determines the per unit price, in `graduated` tiering pricing can successively change as the quantity grows.
   */
  tiersMode?: ("graduated" | "volume") | undefined;
  /**
   * Apply a transformation to the reported usage or set quantity before computing the billed price. Cannot be combined with `tiers`.
   */
  transformUsage?: PlanCreateBodyTransformUsage | undefined;
  /**
   * Default number of trial days when subscribing a customer to this plan using [`trial_from_plan=true`](https://stripe.com/docs/api#create_subscription-trial_from_plan).
   */
  trialPeriodDays?: number | undefined;
  /**
   * Configures how the quantity per period should be determined. Can be either `metered` or `licensed`. `licensed` automatically bills the `quantity` set when adding it to a subscription. `metered` aggregates the total usage based on usage records. Defaults to `licensed`.
   */
  usageType?: ("licensed" | "metered") | undefined;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | (boolean | undefined)
    | (number | undefined)
    | (string | undefined)
    | (("per_unit" | "tiered") | undefined)
    | string
    | (string[] | undefined)
    | (string | undefined)
    | ("day" | "month" | "week" | "year")
    | (number | undefined)
    | ((PlanCreateBodyMetadataObj0 | string) | undefined)
    | (string | undefined)
    | (string | undefined)
    | ((PlanCreateBodyProductObj0 | string) | undefined)
    | (PlanCreateBodyTiersItem[] | undefined)
    | (("graduated" | "volume") | undefined)
    | (PlanCreateBodyTransformUsage | undefined)
    | (number | undefined)
    | (("licensed" | "metered") | undefined)
    | any
    | null
    | undefined;
};

/**
 * @internal
 * PlanCreateBody without any key transformation, this is what
 * we expect to come in as network data
 */
export type External$PlanCreateBody = {
  active?: boolean | undefined;
  amount?: number | undefined;
  amount_decimal?: string | undefined;
  billing_scheme?: ("per_unit" | "tiered") | undefined;
  currency: string;
  expand?: string[] | undefined;
  id?: string | undefined;
  interval: "day" | "month" | "week" | "year";
  interval_count?: number | undefined;
  metadata?: (External$PlanCreateBodyMetadataObj0 | string) | undefined;
  meter?: string | undefined;
  nickname?: string | undefined;
  product?: (External$PlanCreateBodyProductObj0 | string) | undefined;
  tiers?: External$PlanCreateBodyTiersItem[] | undefined;
  tiers_mode?: ("graduated" | "volume") | undefined;
  transform_usage?: External$PlanCreateBodyTransformUsage | undefined;
  trial_period_days?: number | undefined;
  usage_type?: ("licensed" | "metered") | undefined;

  [additionalProperty: string]:
    | (boolean | undefined)
    | (number | undefined)
    | (string | undefined)
    | (("per_unit" | "tiered") | undefined)
    | string
    | (string[] | undefined)
    | (string | undefined)
    | ("day" | "month" | "week" | "year")
    | (number | undefined)
    | ((External$PlanCreateBodyMetadataObj0 | string) | undefined)
    | (string | undefined)
    | (string | undefined)
    | ((External$PlanCreateBodyProductObj0 | string) | undefined)
    | (External$PlanCreateBodyTiersItem[] | undefined)
    | (("graduated" | "volume") | undefined)
    | (External$PlanCreateBodyTransformUsage | undefined)
    | (number | undefined)
    | (("licensed" | "metered") | undefined)
    | External$PlanCreateBody
    | null
    | undefined;
};

/**
 * Takes network data, validates it, and transforms keys to match typescript object PlanCreateBody
 */
const SchemaIn$PlanCreateBody: z.ZodType<
  PlanCreateBody, // output type of this zod object
  z.ZodTypeDef,
  unknown
> = z
  .object({
    active: z.boolean().optional(),
    amount: z.number().int().optional(),
    amount_decimal: z.string().optional(),
    billing_scheme: z.enum(["per_unit", "tiered"]).optional(),
    currency: z.string(),
    expand: z.array(z.string()).optional(),
    id: z.string().optional(),
    interval: z.enum(["day", "month", "week", "year"]),
    interval_count: z.number().int().optional(),
    metadata: z
      .union([Schemas$PlanCreateBodyMetadataObj0.in, z.string()])
      .optional(),
    meter: z.string().optional(),
    nickname: z.string().optional(),
    product: z
      .union([Schemas$PlanCreateBodyProductObj0.in, z.string()])
      .optional(),
    tiers: z.array(Schemas$PlanCreateBodyTiersItem.in).optional(),
    tiers_mode: z.enum(["graduated", "volume"]).optional(),
    transform_usage: Schemas$PlanCreateBodyTransformUsage.in.optional(),
    trial_period_days: z.number().int().optional(),
    usage_type: z.enum(["licensed", "metered"]).optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      active: "active",
      amount: "amount",
      amount_decimal: "amountDecimal",
      billing_scheme: "billingScheme",
      currency: "currency",
      expand: "expand",
      id: "id",
      interval: "interval",
      interval_count: "intervalCount",
      metadata: "metadata",
      meter: "meter",
      nickname: "nickname",
      product: "product",
      tiers: "tiers",
      tiers_mode: "tiersMode",
      transform_usage: "transformUsage",
      trial_period_days: "trialPeriodDays",
      usage_type: "usageType",
    });
  });

/**
 * @internal
 * Takes typescript data, validates it, and maps keys to match the expected external object External$PlanCreateBody
 */
const SchemaOut$PlanCreateBody: z.ZodType<
  External$PlanCreateBody, // output type of this zod object
  z.ZodTypeDef,
  PlanCreateBody // the object to be transformed
> = z
  .object({
    active: z.boolean().optional(),
    amount: z.number().int().optional(),
    amountDecimal: z.string().optional(),
    billingScheme: z.enum(["per_unit", "tiered"]).optional(),
    currency: z.string(),
    expand: z.array(z.string()).optional(),
    id: z.string().optional(),
    interval: z.enum(["day", "month", "week", "year"]),
    intervalCount: z.number().int().optional(),
    metadata: z
      .union([Schemas$PlanCreateBodyMetadataObj0.out, z.string()])
      .optional(),
    meter: z.string().optional(),
    nickname: z.string().optional(),
    product: z
      .union([Schemas$PlanCreateBodyProductObj0.out, z.string()])
      .optional(),
    tiers: z.array(Schemas$PlanCreateBodyTiersItem.out).optional(),
    tiersMode: z.enum(["graduated", "volume"]).optional(),
    transformUsage: Schemas$PlanCreateBodyTransformUsage.out.optional(),
    trialPeriodDays: z.number().int().optional(),
    usageType: z.enum(["licensed", "metered"]).optional(),
  })
  .catchall(zodRequiredAny)
  .transform((obj) => {
    return zodTransform(obj, {
      active: "active",
      amount: "amount",
      amountDecimal: "amount_decimal",
      billingScheme: "billing_scheme",
      currency: "currency",
      expand: "expand",
      id: "id",
      interval: "interval",
      intervalCount: "interval_count",
      metadata: "metadata",
      meter: "meter",
      nickname: "nickname",
      product: "product",
      tiers: "tiers",
      tiersMode: "tiers_mode",
      transformUsage: "transform_usage",
      trialPeriodDays: "trial_period_days",
      usageType: "usage_type",
    });
  });

export const Schemas$PlanCreateBody = {
  in: SchemaIn$PlanCreateBody,
  out: SchemaOut$PlanCreateBody,
};
