/**
 * Reason for the refund, which is either user-provided (`duplicate`, `fraudulent`, or `requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`).
 */
export type RefundReasonEnum =
  | "duplicate"
  | "expired_uncaptured_charge"
  | "fraudulent"
  | "requested_by_customer";
