import { AuthBasic, AuthBearer, CoreClient } from "@sideko-inc/stripe/core";
import { Environment } from "@sideko-inc/stripe/environment";
import { AccountClient } from "@sideko-inc/stripe/resources/account";
import { AccountLinkClient } from "@sideko-inc/stripe/resources/account-link";
import { AccountSessionsClient } from "@sideko-inc/stripe/resources/account-sessions";
import { ApplePayClient } from "@sideko-inc/stripe/resources/apple-pay";
import { ApplicationFeeClient } from "@sideko-inc/stripe/resources/application-fee";
import { AppsClient } from "@sideko-inc/stripe/resources/apps";
import { BalanceClient } from "@sideko-inc/stripe/resources/balance";
import { BalanceTransactionClient } from "@sideko-inc/stripe/resources/balance-transaction";
import { BillingClient } from "@sideko-inc/stripe/resources/billing";
import { BillingPortalClient } from "@sideko-inc/stripe/resources/billing-portal";
import { ChargeClient } from "@sideko-inc/stripe/resources/charge";
import { CheckoutClient } from "@sideko-inc/stripe/resources/checkout";
import { ClimateClient } from "@sideko-inc/stripe/resources/climate";
import { ConfirmationTokenClient } from "@sideko-inc/stripe/resources/confirmation-token";
import { CountrySpecClient } from "@sideko-inc/stripe/resources/country-spec";
import { CouponClient } from "@sideko-inc/stripe/resources/coupon";
import { CreditNoteClient } from "@sideko-inc/stripe/resources/credit-note";
import { CustomerClient } from "@sideko-inc/stripe/resources/customer";
import { CustomerSessionClient } from "@sideko-inc/stripe/resources/customer-session";
import { DisputeClient } from "@sideko-inc/stripe/resources/dispute";
import { EntitlementClient } from "@sideko-inc/stripe/resources/entitlement";
import { EphemeralKeyClient } from "@sideko-inc/stripe/resources/ephemeral-key";
import { EventClient } from "@sideko-inc/stripe/resources/event";
import { ExchangeRateClient } from "@sideko-inc/stripe/resources/exchange-rate";
import { ExternalAccountClient } from "@sideko-inc/stripe/resources/external-account";
import { FileClient } from "@sideko-inc/stripe/resources/file";
import { FileLinkClient } from "@sideko-inc/stripe/resources/file-link";
import { FinancialConnectionsClient } from "@sideko-inc/stripe/resources/financial-connections";
import { ForwardingClient } from "@sideko-inc/stripe/resources/forwarding";
import { IdentityClient } from "@sideko-inc/stripe/resources/identity";
import { InvoiceClient } from "@sideko-inc/stripe/resources/invoice";
import { InvoiceItemClient } from "@sideko-inc/stripe/resources/invoice-item";
import { InvoicePaymentClient } from "@sideko-inc/stripe/resources/invoice-payment";
import { InvoiceRenderingTemplateClient } from "@sideko-inc/stripe/resources/invoice-rendering-template";
import { IssuingClient } from "@sideko-inc/stripe/resources/issuing";
import { LinkAccountSessionClient } from "@sideko-inc/stripe/resources/link-account-session";
import { LinkedAccountClient } from "@sideko-inc/stripe/resources/linked-account";
import { MandatesClient } from "@sideko-inc/stripe/resources/mandates";
import { PaymentIntentClient } from "@sideko-inc/stripe/resources/payment-intent";
import { PaymentLinkClient } from "@sideko-inc/stripe/resources/payment-link";
import { PaymentLinksClient } from "@sideko-inc/stripe/resources/payment-links";
import { PaymentMethodClient } from "@sideko-inc/stripe/resources/payment-method";
import { PaymentMethodConfigurationClient } from "@sideko-inc/stripe/resources/payment-method-configuration";
import { PaymentMethodDomainClient } from "@sideko-inc/stripe/resources/payment-method-domain";
import { PayoutClient } from "@sideko-inc/stripe/resources/payout";
import { PlanClient } from "@sideko-inc/stripe/resources/plan";
import { PriceClient } from "@sideko-inc/stripe/resources/price";
import { ProductClient } from "@sideko-inc/stripe/resources/product";
import { PromotionCodeClient } from "@sideko-inc/stripe/resources/promotion-code";
import { QuoteClient } from "@sideko-inc/stripe/resources/quote";
import { QuotesClient } from "@sideko-inc/stripe/resources/quotes";
import { RadarClient } from "@sideko-inc/stripe/resources/radar";
import { RefundClient } from "@sideko-inc/stripe/resources/refund";
import { ReportingClient } from "@sideko-inc/stripe/resources/reporting";
import { ReviewClient } from "@sideko-inc/stripe/resources/review";
import { SetupAttemptClient } from "@sideko-inc/stripe/resources/setup-attempt";
import { SetupIntentClient } from "@sideko-inc/stripe/resources/setup-intent";
import { ShippingRateClient } from "@sideko-inc/stripe/resources/shipping-rate";
import { SigmaClient } from "@sideko-inc/stripe/resources/sigma";
import { SourceClient } from "@sideko-inc/stripe/resources/source";
import { SubscriptionClient } from "@sideko-inc/stripe/resources/subscription";
import { SubscriptionItemClient } from "@sideko-inc/stripe/resources/subscription-item";
import { SubscriptionScheduleClient } from "@sideko-inc/stripe/resources/subscription-schedule";
import { SubscriptionsClient } from "@sideko-inc/stripe/resources/subscriptions";
import { TaxClient } from "@sideko-inc/stripe/resources/tax";
import { TaxCodeClient } from "@sideko-inc/stripe/resources/tax-code";
import { TaxIdClient } from "@sideko-inc/stripe/resources/tax-id";
import { TaxRateClient } from "@sideko-inc/stripe/resources/tax-rate";
import { TerminalClient } from "@sideko-inc/stripe/resources/terminal";
import { TestHelperClient } from "@sideko-inc/stripe/resources/test-helper";
import { TokenClient } from "@sideko-inc/stripe/resources/token";
import { TopupsClient } from "@sideko-inc/stripe/resources/topups";
import { TransferClient } from "@sideko-inc/stripe/resources/transfer";
import { TransfersClient } from "@sideko-inc/stripe/resources/transfers";
import { TreasuryClient } from "@sideko-inc/stripe/resources/treasury";
import { V1Client } from "@sideko-inc/stripe/resources/v1";
import { WebhookEndpointsClient } from "@sideko-inc/stripe/resources/webhook-endpoints";

export interface StripeOptions {
  baseUrl?: string;
  environment?: Environment;
  timeout?: number;
  username?: string;
  password?: string;
  token?: string;
}

export class Stripe {
  protected _client: CoreClient;
  account: AccountClient;
  applePay: ApplePayClient;
  coupon: CouponClient;
  customer: CustomerClient;
  ephemeralKey: EphemeralKeyClient;
  invoiceItem: InvoiceItemClient;
  invoice: InvoiceClient;
  plan: PlanClient;
  product: ProductClient;
  radar: RadarClient;
  subscriptionItem: SubscriptionItemClient;
  subscription: SubscriptionClient;
  subscriptions: SubscriptionsClient;
  taxId: TaxIdClient;
  terminal: TerminalClient;
  testHelper: TestHelperClient;
  webhookEndpoints: WebhookEndpointsClient;
  applicationFee: ApplicationFeeClient;
  apps: AppsClient;
  balance: BalanceClient;
  balanceTransaction: BalanceTransactionClient;
  billing: BillingClient;
  billingPortal: BillingPortalClient;
  charge: ChargeClient;
  checkout: CheckoutClient;
  climate: ClimateClient;
  v1: V1Client;
  confirmationToken: ConfirmationTokenClient;
  countrySpec: CountrySpecClient;
  creditNote: CreditNoteClient;
  dispute: DisputeClient;
  entitlement: EntitlementClient;
  event: EventClient;
  exchangeRate: ExchangeRateClient;
  fileLink: FileLinkClient;
  file: FileClient;
  financialConnections: FinancialConnectionsClient;
  forwarding: ForwardingClient;
  identity: IdentityClient;
  invoicePayment: InvoicePaymentClient;
  invoiceRenderingTemplate: InvoiceRenderingTemplateClient;
  issuing: IssuingClient;
  linkAccountSession: LinkAccountSessionClient;
  linkedAccount: LinkedAccountClient;
  mandates: MandatesClient;
  paymentIntent: PaymentIntentClient;
  paymentLink: PaymentLinkClient;
  paymentLinks: PaymentLinksClient;
  paymentMethodConfiguration: PaymentMethodConfigurationClient;
  paymentMethodDomain: PaymentMethodDomainClient;
  paymentMethod: PaymentMethodClient;
  payout: PayoutClient;
  price: PriceClient;
  promotionCode: PromotionCodeClient;
  quote: QuoteClient;
  quotes: QuotesClient;
  refund: RefundClient;
  reporting: ReportingClient;
  review: ReviewClient;
  setupAttempt: SetupAttemptClient;
  setupIntent: SetupIntentClient;
  shippingRate: ShippingRateClient;
  sigma: SigmaClient;
  source: SourceClient;
  subscriptionSchedule: SubscriptionScheduleClient;
  tax: TaxClient;
  taxCode: TaxCodeClient;
  taxRate: TaxRateClient;
  token: TokenClient;
  topups: TopupsClient;
  transfer: TransferClient;
  transfers: TransfersClient;
  treasury: TreasuryClient;
  accountLink: AccountLinkClient;
  accountSessions: AccountSessionsClient;
  customerSession: CustomerSessionClient;
  externalAccount: ExternalAccountClient;

  constructor(opts?: StripeOptions) {
    const baseUrl =
      opts?.baseUrl ?? opts?.environment ?? Environment.Production;
    this._client = new CoreClient({ baseUrl, timeout: opts?.timeout });
    this._client.registerAuth(
      "basicAuth",
      new AuthBasic(opts?.username, opts?.password),
    );
    this._client.registerAuth("bearerAuth", new AuthBearer(opts?.token));

    this.account = new AccountClient(this._client);
    this.applePay = new ApplePayClient(this._client);
    this.coupon = new CouponClient(this._client);
    this.customer = new CustomerClient(this._client);
    this.ephemeralKey = new EphemeralKeyClient(this._client);
    this.invoiceItem = new InvoiceItemClient(this._client);
    this.invoice = new InvoiceClient(this._client);
    this.plan = new PlanClient(this._client);
    this.product = new ProductClient(this._client);
    this.radar = new RadarClient(this._client);
    this.subscriptionItem = new SubscriptionItemClient(this._client);
    this.subscription = new SubscriptionClient(this._client);
    this.subscriptions = new SubscriptionsClient(this._client);
    this.taxId = new TaxIdClient(this._client);
    this.terminal = new TerminalClient(this._client);
    this.testHelper = new TestHelperClient(this._client);
    this.webhookEndpoints = new WebhookEndpointsClient(this._client);
    this.applicationFee = new ApplicationFeeClient(this._client);
    this.apps = new AppsClient(this._client);
    this.balance = new BalanceClient(this._client);
    this.balanceTransaction = new BalanceTransactionClient(this._client);
    this.billing = new BillingClient(this._client);
    this.billingPortal = new BillingPortalClient(this._client);
    this.charge = new ChargeClient(this._client);
    this.checkout = new CheckoutClient(this._client);
    this.climate = new ClimateClient(this._client);
    this.v1 = new V1Client(this._client);
    this.confirmationToken = new ConfirmationTokenClient(this._client);
    this.countrySpec = new CountrySpecClient(this._client);
    this.creditNote = new CreditNoteClient(this._client);
    this.dispute = new DisputeClient(this._client);
    this.entitlement = new EntitlementClient(this._client);
    this.event = new EventClient(this._client);
    this.exchangeRate = new ExchangeRateClient(this._client);
    this.fileLink = new FileLinkClient(this._client);
    this.file = new FileClient(this._client);
    this.financialConnections = new FinancialConnectionsClient(this._client);
    this.forwarding = new ForwardingClient(this._client);
    this.identity = new IdentityClient(this._client);
    this.invoicePayment = new InvoicePaymentClient(this._client);
    this.invoiceRenderingTemplate = new InvoiceRenderingTemplateClient(
      this._client,
    );
    this.issuing = new IssuingClient(this._client);
    this.linkAccountSession = new LinkAccountSessionClient(this._client);
    this.linkedAccount = new LinkedAccountClient(this._client);
    this.mandates = new MandatesClient(this._client);
    this.paymentIntent = new PaymentIntentClient(this._client);
    this.paymentLink = new PaymentLinkClient(this._client);
    this.paymentLinks = new PaymentLinksClient(this._client);
    this.paymentMethodConfiguration = new PaymentMethodConfigurationClient(
      this._client,
    );
    this.paymentMethodDomain = new PaymentMethodDomainClient(this._client);
    this.paymentMethod = new PaymentMethodClient(this._client);
    this.payout = new PayoutClient(this._client);
    this.price = new PriceClient(this._client);
    this.promotionCode = new PromotionCodeClient(this._client);
    this.quote = new QuoteClient(this._client);
    this.quotes = new QuotesClient(this._client);
    this.refund = new RefundClient(this._client);
    this.reporting = new ReportingClient(this._client);
    this.review = new ReviewClient(this._client);
    this.setupAttempt = new SetupAttemptClient(this._client);
    this.setupIntent = new SetupIntentClient(this._client);
    this.shippingRate = new ShippingRateClient(this._client);
    this.sigma = new SigmaClient(this._client);
    this.source = new SourceClient(this._client);
    this.subscriptionSchedule = new SubscriptionScheduleClient(this._client);
    this.tax = new TaxClient(this._client);
    this.taxCode = new TaxCodeClient(this._client);
    this.taxRate = new TaxRateClient(this._client);
    this.token = new TokenClient(this._client);
    this.topups = new TopupsClient(this._client);
    this.transfer = new TransferClient(this._client);
    this.transfers = new TransfersClient(this._client);
    this.treasury = new TreasuryClient(this._client);
    this.accountLink = new AccountLinkClient(this._client);
    this.accountSessions = new AccountSessionsClient(this._client);
    this.customerSession = new CustomerSessionClient(this._client);
    this.externalAccount = new ExternalAccountClient(this._client);
  }
}
